name: CI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello-world
        run: echo hello-world
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: test-node
        run: node -v
